-- MySQL Script generated by MySQL Workbench
-- Fri Sep  1 20:33:18 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema solarium
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema solarium
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `solarium` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE `solarium` ;

-- -----------------------------------------------------
-- Table `solarium`.`back_product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `solarium`.`back_product` (
  `id_producto` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(35) NOT NULL,
  `Precio` FLOAT NOT NULL,
  `Stock` INT NOT NULL,
  `id_categoria` INT NOT NULL,
  `id_proveedor` INT NOT NULL,
  PRIMARY KEY (`id_producto`),
  INDEX `fk_producto_categoria1_idx` (`id_categoria` ASC),
  INDEX `fk_producto_proveedor1_idx` (`id_proveedor` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `solarium`.`back_vent`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `solarium`.`back_vent` (
  `id_venta` INT NOT NULL AUTO_INCREMENT,
  `Fecha` DATETIME NOT NULL,
  `Total` FLOAT NOT NULL,
  `empleados_id_empleado` INT NOT NULL,
  `cliente_id_cliente` INT NOT NULL,
  PRIMARY KEY (`id_venta`),
  INDEX `fk_venta_empleados1_idx` (`empleados_id_empleado` ASC),
  INDEX `fk_venta_cliente1_idx` (`cliente_id_cliente` ASC))
ENGINE = MyISAM
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `solarium`.`categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `solarium`.`categoria` (
  `id_categoria` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(35) NOT NULL,
  PRIMARY KEY (`id_categoria`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci ;


-- -----------------------------------------------------
-- Table `solarium`.`cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `solarium`.`cliente` (
  `id_cliente` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(35) NOT NULL,
  `Ape_Paterno` VARCHAR(35) NOT NULL,
  `Ape_Materno` VARCHAR(35) NULL DEFAULT NULL,
  `Email` VARCHAR(50) NOT NULL,
  `Tel` BIGINT NOT NULL,
  `Num_Dir` INT NOT NULL,
  `Calle_Dir` VARCHAR(50) NOT NULL,
  `C_P_Dir` VARCHAR(6) NOT NULL,
  `Col_Dir` VARCHAR(45) NOT NULL,
  `Mun_Dir` VARCHAR(50) NOT NULL,
  `Est_Dir` VARCHAR(50) NOT NULL,
  `Tipo_Proyect` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id_cliente`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci ;


-- -----------------------------------------------------
-- Table `solarium`.`empleados`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `solarium`.`empleados` (
  `id_empleado` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(35) NOT NULL,
  `Ape_Paterno` VARCHAR(35) NOT NULL,
  `Ape_Materno` VARCHAR(35) NULL DEFAULT NULL,
  `Email` VARCHAR(50) NOT NULL,
  `Tel` BIGINT NOT NULL,
  PRIMARY KEY (`id_empleado`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci ;


-- -----------------------------------------------------
-- Table `solarium`.`producto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `solarium`.`producto` (
  `id_producto` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(35) NOT NULL,
  `Precio` FLOAT NOT NULL,
  `Stock` INT NOT NULL,
  `id_categoria` INT NOT NULL,
  `id_proveedor` INT NOT NULL,
  PRIMARY KEY (`id_producto`),
  INDEX `fk_producto_categoria1_idx` (`id_categoria` ASC),
  INDEX `fk_producto_proveedor1_idx` (`id_proveedor` ASC))
ENGINE = MyISAM
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `solarium`.`proveedor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `solarium`.`proveedor` (
  `id_proveedor` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(35) NOT NULL,
  `Email` VARCHAR(50) NOT NULL,
  `Pag` VARCHAR(150) NULL DEFAULT NULL,
  PRIMARY KEY (`id_proveedor`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci ;


-- -----------------------------------------------------
-- Table `solarium`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `solarium`.`usuario` (
  `idUsuario` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(45) NOT NULL,
  `Contraseña` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idUsuario`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci ;


-- -----------------------------------------------------
-- Table `solarium`.`venta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `solarium`.`venta` (
  `id_venta` INT NOT NULL AUTO_INCREMENT,
  `Fecha` DATETIME NOT NULL,
  `Total` FLOAT NOT NULL,
  `id_empleado` INT NOT NULL,
  `id_cliente` INT NOT NULL,
  PRIMARY KEY (`id_venta`),
  INDEX `fk_venta_empleados1_idx` (`id_empleado` ASC),
  INDEX `fk_venta_cliente1_idx` (`id_cliente` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci ;


-- -----------------------------------------------------
-- Table `solarium`.`venta_tiene_productos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `solarium`.`venta_tiene_productos` (
  `id_venta_tiene_productos` INT NOT NULL AUTO_INCREMENT,
  `Precio` FLOAT NOT NULL,
  `Cantidad` INT NOT NULL,
  `id_producto` INT NOT NULL,
  `id_venta` INT NOT NULL,
  PRIMARY KEY (`id_venta_tiene_productos`),
  INDEX `fk_venta_tiene_productos_producto_idx` (`id_producto` ASC),
  INDEX `fk_venta_tiene_productos_venta1_idx` (`id_venta` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci ;

USE `solarium`;

DELIMITER $$
USE `solarium`$$
CREATE
DEFINER=`root`@`localhost`
TRIGGER `solarium`.`respaldo`
AFTER INSERT ON `solarium`.`producto`
FOR EACH ROW
begin
  INSERT INTO back_product(Nombre,Precio,Stock,id_categoria,id_proveedor)
  VALUES(NEW.Nombre,NEW.Precio,NEW.Stock,NEW.id_categoria,NEW.id_proveedor);
 end$$

USE `solarium`$$
CREATE
DEFINER=`root`@`localhost`
TRIGGER `solarium`.`ventarespaldo`
BEFORE INSERT ON `solarium`.`venta`
FOR EACH ROW
begin
INSERT INTO back_vent(Fecha,Total,id_cliente,id_empleado)
VALUES(NEW.Fecha,NEW.Total,NEW.id_cliente,NEW.id_empleado);
 end$$


DELIMITER ;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
